apiVersion: v1
kind: Namespace
metadata:
  name: fusionauth
  labels:
    aws.conformance.vendor: fusionauth
    aws.conformance.vendor-solution: fusionauth
    aws.conformance.vendor-solution-version: "latest"

