apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 15m0s
  install:
    timeout: 15m0s
    remediation:
      retries: 3
  upgrade:
    timeout: 15m0s
    remediation:
      retries: 3
  chart:
    spec:
      chart: postgresql
      version: 16.7.27
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      # Admin (superuser)
      username: postgres
      password: changeMeSuperSecret
      # Create an application database for FusionAuth
      database: fusionauth
    primary:
      persistence:
        enabled: false  # disable PVCs for EKS-A docker dev env; set true if you have storageclass

