apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  timeout: 15m0s
  install:
    timeout: 15m0s
    remediation:
      retries: 3
  upgrade:
    timeout: 15m0s
    remediation:
      retries: 3

  # Make FA wait on Postgres
  dependsOn:
    - name: postgres
      namespace: fusionauth

  chart:
    spec:
      chart: fusionauth
      # version: 1.59.1  # optional pin
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system

  values:
    # --- Database settings ---
    database:
      protocol: postgresql
      host: postgres-postgresql.fusionauth.svc.cluster.local
      port: 5432
      name: fusionauth
      # Application user (least-priv)
      user: postgres
      password: changeMeSuperSecret

    # Use database search (no Elasticsearch)
    search:
      engine: database
    
    app:
      runtimeMode: development
        
    # Simple exposure for EKS-A Docker
    service:
      type: NodePort
    ingress:
      enabled: false
      
  
