apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusionauth
  namespace: fusionauth
spec:
  interval: 10m
  chart:
    spec:
      chart: fusionauth
      version: "*" 
      sourceRef:
        kind: HelmRepository
        name: fusionauth
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: fusionauth-values
      valuesKey: fusionauth.yaml
  values: {}

