# ClusterSecretStore for AWS SM
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2   # <-- replace with your AWS region
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secret
            namespace: external-secrets
            key: secret-access-key
---
# ExternalSecret to project DB password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fusionauth-db-creds
  namespace: fusionauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: fusionauth-db-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: fusionauth/prod/db
        property: password

