apiVersion: batch/v1
kind: Job
metadata:
  name: sysdig-agent-tester
  namespace: sysdig
spec:
  template:
    spec:
      serviceAccountName: 'sysdig-agent'
      containers:
        - name: test-sysdig-agent
          image: 'alpine/k8s:1.26.2'
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - '-c'
            - >-
              echo 1. Checking readiness probe
              sysdig_pod="...";
              while [[ "$sysdig_pod" != "sysdig-agent-"* ]]; 
              do sysdig_pod=`kubectl get pod -n sysdig -l app=sysdig-agent --field-selector=status.phase==Running -o jsonpath="{.items[0].metadata.name}"` && echo Waiting;
              sleep 15;
              done;
              echo 2. Checking audit port
              sysdig_audit="...";
              while [[ "$sysdig_audit" != *"Connected"* ]];
              do sysdig_audit=`curl -ksv --connect-timeout 4 telnet://sysdig-agent.sysdig.svc.cluster.local:7765 2>&1` && echo Connecting;
              sleep 2;
              done;          
              echo Success;
      restartPolicy: Never
  backoffLimit: 1
