apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube-token-secret
  namespace: botkube
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: botkube-secret # Secret name in k8s
  data:
  - secretKey: botkube-token # which key it's going to be stored
    remoteRef:
      key: botkube-token # Our secret-name goes here