---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulumi-tester-rolebinding
  namespace: pulumi
subjects:
  - kind: ServiceAccount
    name: pulumi-tester
roleRef:
  kind: Role
  name: pulumi-tester-role
  apiGroup: rbac.authorization.k8s.io
