apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pulumi-access-token
  namespace: pulumi
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: pulumi-access-token # Secret name in k8s
  data:
    - secretKey: pulumi-access-token # which key it's going to be stored
      remoteRef:
        key: value # Our secret-name goes here
