---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulumi-tester-role
  namespace: pulumi
rules:
  - apiGroups: ["pulumi.com"]
    resources: ["stacks", "programs"]
    verbs: ["*"]
