apiVersion: batch/v1
kind: CronJob
metadata:
  name: observer
  namespace: observer
spec:
  # Run at the top of every hour
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: observer-sa
          containers:
          - name: observer-pod
            image: 771830474512.dkr.ecr.us-east-1.amazonaws.com/observer-bot:latest
            imagePullPolicy: Always
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: observer-key
                    key: observer_token
          restartPolicy: Never