apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::771830474512:role/observer-bot-sa
  name: observer-secret-sa
  namespace: observer
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: observer-store
  namespace: observer
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: observer-secret-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observer-secret
  namespace: observer
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: observer-store
    kind: SecretStore
  target:
    name: observer-key
    creationPolicy: Owner
  data:
  - secretKey: observer-key
    remoteRef:
      key: observer_token
      property: github_token