apiVersion: v1
kind: ServiceAccount
metadata:
  name: observer-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watch-pods
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attach-observer-role-to-sa
subjects:
  - kind: ServiceAccount
    name: observer-kubectl
roleRef:
  kind: Role
  name: watch-pods
  apiGroup: rbac.authorization.k8s.io