apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::771830474512:role/cluster1-stack-cluster1stackobserverbot-sa
  name: observer-sa
  namespace: observer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-pods
rules:
  - apiGroups: ["*"]
    resources: 
      - "pods"
      - "namespaces"
      - "replicasets"
      - "statefulsets"
      - "daemonset"
      - "jobs"
      - "services"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: attach-observer-role-to-sa
  namespace: observer
subjects:
  - kind: ServiceAccount
    name: observer-sa
    namespace: observer
roleRef:
  kind: ClusterRole
  name: watch-pods
  apiGroup: rbac.authorization.k8s.io