apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observer-secret
  namespace: observer
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: eksa-secret-store
    kind: ClusterSecretStore
  target:
    name: observer-key
    creationPolicy: Owner
  data:
  - secretKey: observer-key
    remoteRef:
      key: github-token
