apiVersion: batch/v1
kind: CronJob
metadata:
  name: observer
spec:
  # Run at the top of every hour
  schedule: "0 * * * *"
  serviceAccountName: observer-sa
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
          restartPolicy: OnFailure
