apiVersion: v1
kind: ServiceAccount
metadata:
  name: observer-sa
  namespace: observer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-pods
rules:
  - apiGroups: ["*"]
    resources: 
      - "pods"
      - "namespaces"
      - "replicasets"
      - "deployments"
      - "statefulsets"
      - "daemonset"
      - "jobs"
      - "services"
      - "configmaps"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modified-configmap
  namespace: observer
rules:
  - apiGroups:
      - "*" # Represents core api group?
    resources:
      - "configmaps"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: attach-observer-role-to-sa
  namespace: observer
subjects:
  - kind: ServiceAccount
    name: observer-sa
    namespace: observer
roleRef:
  kind: ClusterRole
  name: watch-pods
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attach-configmap-role-to-sa
  namespace: observer
subjects:
  - kind: ServiceAccount
    name: observer-sa
    namespace: observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modified-configmap