apiVersion: batch/v1
kind: CronJob
metadata:
  name: observer
  namespace: observer
spec:
  # Run at the top of every hour
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: observer-sa
          containers:
          - name: observer-pod
            image: public.ecr.aws/n5p5f4n3/conformitron-observer-bot:multiarch
            imagePullPolicy: Always
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: observer-key
                    key: observer-key
              - name: REPO
                value: eks-anywhere-addons
              - name: OWNER
                value: aws-samples
          restartPolicy: Never
