apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-baremetal-manifestjob
  namespace: default
spec:
  schedule: "12 12 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: job
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo sleeping....; sleep 5s; exit 0;
          restartPolicy: Never