apiVersion: batch/v1
kind: Job
metadata:
  name: komodor-tester
  namespace: komodor
spec:
  template:
    spec:
      containers:
        - name: job
          image: 'alpine/k8s:1.26.2'
          imagePullPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
            - >-
              echo 1. Checking readiness probe for watcher
              k8s_watcher_pod="...";
              while [[ "$k8s_watcher_pod" != "komodor-k8s-watcher-"* ]]; 
              do k8s_watcher_pod=`kubectl get pod -n komodor -l app.kubernetes.io/name=k8s-watcher --field-selector=status.phase==Running -o jsonpath="{.items[0].metadata.name}"` && echo Waiting;
              sleep 15;
              echo pod $k8s_watcher_pod is ready;
              done;        
              echo Success;
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-listing-role
  namespace: komodor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-listing-rolebinding
  namespace: komodor
subjects:
- kind: ServiceAccount
  name: default
  namespace: komodor
roleRef:
  kind: Role
  name: pod-listing-role
  apiGroup: rbac.authorization.k8s.io