apiVersion: batch/v1
kind: Job
metadata:
  name: komodor-tester
  namespace: komodor
spec:
  template:
    spec:
      containers:
        - name: job
          image: 'public.ecr.aws/komodor-public/k8s-watcher:test-arm'
          env:
            - name: KOMOKW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-watcher-secret-flux
                  key: k8s-watcher-apiKey
            - name: KOMOKW_CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: k8s-watcher-secret-flux
                  key: k8s-watcher-clusterName             
          imagePullPolicy: Always

          command: [ "/bin/sh", "-c", "--"]
          args:
          - >-
            echo 1. Checking readiness probe for watcher
            k8s_watcher_pod="...";
            while [[ "$k8s_watcher_pod" != "komodor-k8s-watcher-"* ]]; 
            do k8s_watcher_pod=`kubectl get pod -n komodor -l app.kubernetes.io/name=k8s-watcher --field-selector=status.phase==Running -o jsonpath="{.items[0].metadata.name}"` && echo Waiting;
            sleep 15;
            
            echo "Running connectivity test" ;
            arch=$(uname -m)

            case "$arch" in
                aarch64)
                    architecture="amd64"
                    ;;
                x86_64)
                    exec /opt/watcher-linux-amd64 test -connectivity
                    ;;
                *)
                    architecture="arm64"
                    ;;
            esac            
            /opt/watcher-linux-$architecture test -connectivity;
            
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-listing-role
  namespace: komodor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-listing-rolebinding
  namespace: komodor
subjects:
- kind: ServiceAccount
  name: default
  namespace: komodor
roleRef:
  kind: Role
  name: pod-listing-role
  apiGroup: rbac.authorization.k8s.io