apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-configmap
  namespace: podinfo
  labels:
    bot: conformitron
data:
  Namespace: podinfo
  prNumber: "16"
  commitHash: 9c17c0015d6ebd78e2ec035dbafaf2e0457e744c
