---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
  namespace: kubecost
spec:
  chart:
    spec:
      chart: cost-analyzer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubecost-charts
        namespace: flux-system
      version: 2.0.2
  interval: 1m0s
  targetNamespace: kubecost
  valuesFrom:
  - kind: Secret
    name: kubecost-secret
    valuesKey: kubecost-token
    targetPath: kubecostToken
