---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dynatrace-operator
  namespace: flux-system
spec:
  path: "./eks-anywhere-common/Addons/Partner/dynatrace/dynatrace-operator"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dynakube
  namespace: flux-system
spec:
  dependsOn:
    - name: dynatrace-operator
  path: "./eks-anywhere-common/Addons/Partner/dynatrace/dynatrace-dynakube"
  sourceRef:
    kind: GitRepository
    name: addons
    namespace: flux-system
  interval: 5m0s
  prune: true
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: dynatrace-variables # Provides apiurl, dynatracesecretname, dynakubename, oneagentvolumestorage