---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynatrace-variables
  namespace: flux-system
data:
  # api url for dynatrace environment 
  apiurl: "<replaceme>"
  # name of secret containing tokens
  dynatracesecretname: "dt-secret"
  # name of cluster to be listed in Dynatrace
  dynakubename: "<replaceme>"
