---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynatrace-variables
  namespace: flux-system
data:
  # name of secret containing tokens created by external-secret
  dynatracesecretname: "dt-secret"
  # name of cluster to be listed in Dynatrace
  dynakubename: "eks-flux-test-cluster"
