apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "305"
  commitHash: 85b04bbd49a4f8f8c13ec5bf0434c040fcfcd710
  deployed: "1729633141"
  env: vsphere
