apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "352"
  commitHash: f4695e5f38addc9b3776b1e36efe4ab687926a98
  deployed: "1740676829"
  env: vsphere
