apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "336"
  commitHash: b8d78e433a546ea4758b130c56456dfc1e32f031
  deployed: "1738102264"
  env: vsphere
