apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "353"
  commitHash: 2c5bc78045b85ae2d1af325a417c2bf9bd8f68f3
  deployed: "1742507410"
  env: cloud
