apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "351"
  commitHash: 6c7a61d54cda7d19aed604cea8a4c707bc7ea519
  deployed: "1740431004"
  env: cloud
