apiVersion: batch/v1
kind: Job
metadata:
  name: kong-enterprise-testjob
  namespace: kong
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: job
          image: curlimages/curl
          command: ["curl", "-ks", "--location", "http://eks-anywhere-kong-proxy.kong.svc.cluster.local:80"]
      restartPolicy: Never