---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-gateway-job
  namespace: kong
rules:
  - apiGroups: [ "" ]
    resources: ["pods","services"]
    verbs: [ "get","list","create", "update", "patch", "watch" ]
  - apiGroups: [ "apps" ]
    resources: ["deployments"]
    verbs: [ "get", "create", "update", "patch" ]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: [ "get", "create", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-test
  namespace: kong
subjects:
  - kind: User
    name: system:serviceaccount:kong:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kong-gateway-job
  apiGroup: rbac.authorization.k8s.io
