apiVersion: batch/v1
kind: Job
metadata:
  name: k10-primer-job
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: k10-primer
          image: 'alpine:latest'
          command:
            - /bin/sh
          args:
            - -c
            - >-
              apk add --no-cache helm curl bash jq;
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl";
              install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl;
              helm repo add kasten https://charts.kasten.io/
              kubectl version && ( curl -s https://docs.kasten.io/tools/k10_primer.sh  | bash /dev/stdin -s ebs-sc);
      restartPolicy: Never