apiVersion: batch/v1
kind: Job
metadata:
  name: k10-primer-job
  namespace: kasten-io
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: kasten-io-k10-k10
      containers:
        - name: k10-primer
          image: 'alpine:latest'
          command:
            - /bin/sh
          args:
            - -c
            - >-
              SC_NAME="ebs-sc";
              VSC_NAME="csi-aws-vsc";
              apk add --no-cache helm curl bash jq;
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl";
              install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl;
              helm repo add kasten https://charts.kasten.io/;
              kubectl annotate volumesnapshotclass ${VSC_NAME} k10.kasten.io/is-snapshot-class=true;
              curl -s https://docs.kasten.io/tools/k10_primer.sh  | bash /dev/stdin -s ${SC_NAME};
              kubectl annotate volumesnapshotclass ${VSC_NAME} k10.kasten.io/is-snapshot-class-;
      restartPolicy: Never