---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: perfectscale
  namespace: perfectscale
spec:
  chart:
    spec:
      chart: exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: perfectscale-charts
        namespace: flux-system
      version: v0.0.38
  interval: 1m0s
  targetNamespace: perfectscale
  values:
    secret:
      create:
        true
  valuesFrom:
  - kind: Secret
    name: perfectscale-sm-secret
    valuesKey: clientId
    targetPath: secret.clientId
  - kind: Secret
    name: perfectscale-sm-secret
    valuesKey: clientSecret
    targetPath: secret.clientSecret   