apiVersion: batch/v1
kind: CronJob
metadata:
  name: datakit-test-cronjob
  namespace: datakit
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datakit-test-cronjob
              image: busybox:1.36
              command: ["/bin/sh", "-c"]
              args:
                - |
                  response=$(curl -s -w "%{http_code}" -X POST \
                    -H "Content-Type: application/json" \
                    -d '[{"measurement":"test_log","tags":{"foo":"bar"},"fields":{"message":"This log from aws service ready tester."}}]' \
                    http://datakit-service.datakit.svc.cluster.local:9529/v1/write/logging)

                  http_code=${response: -3}

                  if [ $http_code -ge 200 ] && [ $http_code -lt 300 ]; then
                      echo "Write log success."
                  else
                      echo "Write log failed."
                      exit 1
                  fi
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
