apiVersion: batch/v1
kind: CronJob
metadata:
  name: datakit-test-cronjob
  namespace: default
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datakit-test-cronjob
              image: busybox:1.36
              command: ["/bin/sh", "-c"]
              args:
                - |
                  RESPONSE=$(wget -qO- --server-response --timeout=10 "http://datakit-service.datakit.svc.cluster.local:9529/v1/ping" 2>&1)
                  HTTP_CODE=$(echo "$RESPONSE" | awk '/^  HTTP/{print $2}' | tail -1)
                  BODY="{${RESPONSE##*{}"
                  if [ "$HTTP_CODE" = "200" ]; then
                    echo "Datakit is available, info: ${BODY}"
                    exit 0
                  else
                    echo "Datakit is unavailable, v1/ping endpoint http response code: ${HTTP_CODE}, please check the pod status and security policies"
                    exit 1
                  fi
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
