---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ebs-csi-driver
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
      version: 2.11.1
  interval: 60s
  targetNamespace: kube-system
  values: 
    controller:
      region: snow
    node:
      env:
      - name: AWS_REGION
        value: snow
  
