apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: komodor-external-secret
  namespace: komodor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store 
    kind: ClusterSecretStore
  target:
    name: k8s-watcher-secret-flux
  data:
  - secretKey: k8s-watcher-apiKey 
    remoteRef:
      key: k8s-watcher-apiKey
  - secretKey: k8s-watcher-clusterName  
    remoteRef:
      key: k8s-watcher-clusterName