---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stormforge-external-secret
  namespace: stormforge
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: eksa-secret-store
    kind: ClusterSecretStore
  target:
    name: stormforge-auth-secret
  data:
  - secretKey: clientID
    remoteRef:
      key: stormforge-secrets
      property: clientID
  - secretKey: clientSecret
    remoteRef:
      key: stormforge-secrets
      property: clientSecret
