---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stormforge-configmaps-admin
  namespace: stormforge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stormforge-configmaps-admin
  namespace: stormforge
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["*"] # full access
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stormforge-configmaps-admin
  namespace: stormforge
subjects:
  - kind: ServiceAccount
    name: stormforge-configmaps-admin
    namespace: stormforge
roleRef:
  kind: Role
  name: stormforge-configmaps-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stormforge-cluster-name
  namespace: stormforge
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: stormforge-configmaps-admin
      containers:
      - name: generate-name
        image: bitnami/kubectl:1.31
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - '/bin/sh'
        - '-c'
        - |
          cm_name=stormforge-clustername
          cluster_name="eksa-test-$(LC_ALL=C tr -dc a-z0-9 </dev/urandom | head -c 7; echo)"
          kubectl create configmap "$cm_name" -n "$NAMESPACE" --from-literal clusterName="$cluster_name"
