---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stormforge-charts
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry.stormforge.io/library
