---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stormforge-agent-release
  namespace: stormforge
spec:
  releaseName: stormforge-agent
  chart:
    spec:
      chart: stormforge-agent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stormforge-charts
        namespace: flux-system
      version: 2.16.1
  interval: 5m0s
  targetNamespace: stormforge
  valuesFrom:
  - kind: ConfigMap
    name: stormforge-clustername
    valuesKey: clusterName
    targetPath: clusterName
  - kind: Secret
    name: stormforge-auth-secret
    valuesKey: clientID
    targetPath: authorization.clientID
  - kind: Secret
    name: stormforge-auth-secret
    valuesKey: clientSecret
    targetPath: authorization.clientSecret
