apiVersion: batch/v1
kind: CronJob
metadata:
  name: thinkingengine-health-test
  namespace: thinkingengine
spec:
  schedule: "10 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: tester
              image: alpine/k8s:1.26.2
              command: ["/bin/bash", "-c"]
              args:
                - |-
                  echo "Starting ThinkingEngine health test..."
                 
                  response=$(curl --silent -i http://thinkingengine-trino.thinkingengine:8080/v1/info)
                  response_status=$(echo $response | awk '/^HTTP/{print $2}')

                  if [[ $response_status == "200" && $response == *"nodeVersion"* ]]; then 
                    echo -e "Success: ThinkingEngine is running, health test passed."
                    exit 0
                  else
                    echo -e "Error: ThinkingEngine is running, health test failed."
                    exit 1
                  fi
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1