apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi