apiVersion: batch/v1
kind: CronJob
metadata:
  name: fusionauth-status-check
  namespace: fusionauth
  labels:
    aws.conformance.vendor: fusionauth
    aws.conformance.vendor-solution: fusionauth
    aws.conformance.vendor-solution-version: "latest"
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              image: curlimages/curl:8.8.0
              args:
                - /bin/sh
                - -c
                - >
                  set -e;
                  URL="http://fusionauth.fusionauth.svc.cluster.local:9011/api/status";
                  echo "Hitting ${URL} ...";
                  CODE=$(curl -s -o /dev/null -w "%{http_code}" "$${URL}");
                  echo "HTTP $${CODE}";
                  test "$${CODE}" = "200";

