---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: thinkingengine
  namespace: flux-system
spec:
  interval: 30s
  url: 	https://docker-ta.thinkingdata.cn/chartrepo/thinkingengine