apiVersion: batch/v1
kind: CronJob
metadata:
  name: automq-health-perf-test
  namespace: automq
spec:
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: automq-perf-tester
              image: automqinc/automq:1.5.0-bitnami
              imagePullPolicy: IfNotPresent
              workingDir: /tmp
              command: ["/bin/sh", "-c"]
              args:
                - |-
                  echo "Starting AutoMQ health and performance test..."

                  SERVICE_HOST="automq-release-kafka.automq.svc.cluster.local"
                  SERVICE_PORT="9092"

                  # Test Kafka connectivity directly, skip network check
                  echo "Testing Kafka connectivity directly..."

                  timeout 20 kafka-broker-api-versions.sh --bootstrap-server ${SERVICE_HOST}:${SERVICE_PORT} >/dev/null 2>&1
                  if [ $? -eq 0 ]; then
                    echo "Kafka connectivity test passed."
                    # Continue with performance test
                  else
                    echo "Error: Cannot connect to Kafka broker"
                    exit 1
                  fi

                  # Performance test
                  cd /tmp && automq-perf-test.sh \
                    --bootstrap-server ${SERVICE_HOST}:${SERVICE_PORT} \
                    --producer-configs batch.size=0 \
                    --consumer-configs fetch.max.wait.ms=1000 \
                    --topics 10 \
                    --partitions-per-topic 12 \
                    --producers-per-topic 1 \
                    --groups-per-topic 1 \
                    --consumers-per-group 1 \
                    --record-size 200 \
                    --send-rate 100 \
                    --warmup-duration 0 \
                    --test-duration 1 \
                    --reset

                  TEST_EXIT_CODE=$?
                  if [ ${TEST_EXIT_CODE} -eq 0 ]; then
                    echo "Success: Performance test completed without errors."
                    exit 0
                  else
                    echo "Error: Performance test failed with exit code ${TEST_EXIT_CODE}."
                    exit 1
                  fi
          restartPolicy: OnFailure
      backoffLimit: 1
