---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solo-istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: solo-istiod
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: solo-istiod-charts
        namespace: flux-system
      version: 1.18.3
  interval: 1m0s
