---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
      aws.conformance.vendor: hashicorp
      aws.conformance.vendor-solution: vault
      aws.conformance.vendor-solution-version: 0.25.0