apiVersion: v1
kind: ConfigMap
metadata:
  name: automq-configmap
  namespace: automq
  labels:
    bot: conformitron
data:
  Namespace: automq
  prNumber: "375"
  commitHash: 9e0c3b9db8510af2285f81fc689f7ceec0c28458
  deployed: "1754472748"
  env: common
