apiVersion: v1
kind: ConfigMap
metadata:
  name: automq-configmap
  namespace: automq
  labels:
    bot: conformitron
data:
  Namespace: automq
  prNumber: "375"
  commitHash: d9d780ff1ed1d1f88001f519def8b49442c830fc
  deployed: "1754376084"
  env: common
