apiVersion: v1
kind: ConfigMap
metadata:
  name: automq-configmap
  namespace: automq
  labels:
    bot: conformitron
data:
  Namespace: automq
  prNumber: "375"
  commitHash: 73470532ac363c7d3a94c9959d553c01d12057ad
  deployed: "1754492359"
  env: common
