apiVersion: v1
kind: ConfigMap
metadata:
  name: automq-configmap
  namespace: automq
  labels:
    bot: conformitron
data:
  Namespace: automq
  prNumber: "375"
  commitHash: b80c9baf267cecbe9d48aafd793a596e7c8b595a
  deployed: "1756155024"
  env: common
