apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "333"
  commitHash: cee4d7164d783fc6e273546cb7b0e9fce5740893
  deployed: "1735646570"
  env: nodes
