apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "366"
  commitHash: adaf424d3c05ba568122a82ff69ad3d9e6fd5315
  deployed: "1749141533"
  env: nodes
