apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-external-secret
  namespace: newrelic
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: newrelic-secret # Secret name in k8s
  data:
  - secretKey: newrelic-licensekey # which key it's going to be stored
    remoteRef:
      key: newrelic-licensekey # Our secret-name goes here
  - secretKey: newrelic-account 
    remoteRef:
      key: newrelic-account 
  - secretKey: newrelic-apikey # which key it's going to be stored
    remoteRef:
      key: newrelic-apikey