---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubecost-charts
  namespace: flux-system
spec:
  interval: 30s
  url: https://kubecost.github.io/cost-analyzer/

