apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: perfectscale-external-secret
  namespace: perfectscale
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store
    kind: ClusterSecretStore
  target:
    name: perfectscale-sm-secret
  data:
  - secretKey: clientId
    remoteRef:
      key: perfectscale-secrets
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: perfectscale-secrets
      property: clientSecret