apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wa-external-secret
  namespace: wave-autoscale
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: wa-secret # Secret name in k8s
  data:
    - secretKey: WA_LICENSE
      remoteRef:
        key: WA_LICENSE
    - secretKey: GHRC_TOKEN
      remoteRef:
        key: GHRC_TOKEN
