---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wave-autoscale-agent
  namespace: wave-autoscale
spec:
  chart:
    spec:
      chart: wave-autoscale-agent-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wave-autoscale-agent-helm
        namespace: flux-system
      version: 1.8.0
  interval: 1m0s
  targetNamespace: wave-autoscale
  values:
    ghcr:
      enabled: true
    spec:
      agent:
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
      cadvisor:
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
  valuesFrom:
    - kind: Secret
      name: wa-secret
      valuesKey: GHRC_TOKEN
      targetPath: ghcr.dockerconfigjson
