---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wave-autoscale
  namespace: wave-autoscale
spec:
  chart:
    spec:
      chart: wave-autoscale-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wave-autoscale-helm
        namespace: flux-system
      version: 1.10.0
  interval: 1m0s
  targetNamespace: wave-autoscale
  values:
    ghcr:
      enabled: true
    spec:
      core:
        env:
          - name: WA_LICENSE
            valueFrom:
              secretKeyRef:
                name: wa-secret
                key: WA_LICENSE
          - name: WA_API_SERVER_HOST
            value: "0.0.0.0"
  valuesFrom:
    - kind: Secret
      name: wa-secret
      valuesKey: GHRC_TOKEN
      targetPath: ghcr.dockerconfigjson
