---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wave-autoscale
  namespace: wave-autoscale
spec:
  chart:
    spec:
      chart: wave-autoscale-helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wave-autoscale-helm
        namespace: flux-system
      version: 1.10.0
  interval: 1m0s
  targetNamespace: wave-autoscale
  values:
    spec:
      core:
        env:
          - name: WA_LICENSE
            value: ""
  valuesFrom:
    - kind: Secret
      name: wa-secret
      valuesKey: WA_LICENSE
      targetPath: core.env.0.value
    - kind: Secret
      name: wa-secret
      valuesKey: GHRC_TOKEN
      targetPath: ghcr.dockerconfigjson
