apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-configmap
  namespace: sysdig
  labels:
    bot: conformitron
data:
  Namespace: sysdig
  prNumber: "315"
  commitHash: ff486a2047ef351a5e8dd78b23c9c326f02f43da
  deployed: "1732041275"
  env: common
