apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sysdig-secretstore-ekssnow
  namespace: sysdig
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store             #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: sysdig-access-key             # Secret name in k8s
  data:
  - secretKey: secret-sysdig-key        # which key it's going to be stored
    remoteRef:
      key: secret-sysdig-key            # Our secret-name goes here
