apiVersion: v1
kind: ConfigMap
metadata:
  name: vmware-system-csi-configmap
  namespace: vmware-system-csi
  labels:
    bot: conformitron
data:
  Namespace: vmware-system-csi
  prNumber: "376"
  commitHash: 695612c9553b18822d9e214ad999b32ef44c8bc2
  deployed: "1754069655"
  env: vsphere
