apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  chart:
    spec:
      chart: k10
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      version: 7.5.10
  interval: 1m0s
  targetNamespace: kasten-io
  values:
    eula:
      accept: true
      company: "AWS EKS-A Validation"
      email: "validation@example.com"
    global:
      persistence:
        storageClass: "ebs-sc" # Assuming EBS CSI driver creates this storage class