apiVersion: v1
kind: Namespace
metadata:
    name: kasten-io
    labels:
        aws.conformance.vendor: veeam
        aws.conformance.vendor-solution: kasten
        aws.conformance.vendor-solution-version: 7.5.10