apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubecost-healthtest
  namespace: kubecost
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - name: test-kubecost
              image: alpine/k8s:1.26.9
              command:
                - /bin/sh
              args:
                - -c
                - >-
                  echo Getting current Kubecost state.;
                  response=$(curl -sL http://kubecost-cost-analyzer:9090/model/getConfigs);
                  code=$(echo ${response} | jq .code);
                  if [ "$code" -eq 200 ]; then
                    echo "Got Kubecost working configuration. Successful."
                    exit 0
                  else 
                    echo "Failed to fetch Kubecost configuration. Response was $response"
                    exit 1
                  fi
          restartPolicy: Never
      backoffLimit: 1
