---
apiVersion: batch/v1
kind: Job
metadata:
  name: k10-primer-job
  namespace: kasten-io
spec:
  template:
    spec:
      serviceAccountName: kube-admin
      containers:
        - name: k10-primer
          image: 'ghcr.io/kanisterio/kubectl:latest'
          command:
            - /bin/sh
          args:
            - '-c'
            - >-
              curl -s https://docs.kasten.io/tools/k10_primer.sh  | bash /dev/stdin -s ebs-sc
      restartPolicy: Never
  backoffLimit: 4