apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lacework-external-secret
  namespace: lacework
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: lacework-secrets
  data:
  - secretKey: accessToken
    remoteRef:
      key: lacework-secrets
      property: accessToken
  - secretKey: k8sCluster
    remoteRef:
      key: lacework-secrets
      property: k8sCluster
  - secretKey: environment
    remoteRef:
      key: lacework-secrets
      property: environment
  - secretKey: serverUrl
    remoteRef:
      key: lacework-secrets
      property: serverUrl