---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lacework-agent
  namespace: lacework
spec:
  chart:
    spec:
      chart: lacework-agent
      sourceRef:
        kind: HelmRepository
        name: lacework
        namespace: lacework
  interval: 1m0s
  targetNamespace: lacework
  valuesFrom:
    - kind: Secret
      name: lacework-secrets
      valuesKey: accessToken
      targetPath: laceworkConfig.accessToken
    - kind: Secret
      name: lacework-secrets
      valuesKey: k8sCluster
      targetPath: laceworkConfig.kubernetesCluster
    - kind: Secret
      name: lacework-secrets
      valuesKey: environment
      targetPath: laceworkConfig.env
    - kind: Secret
      name: lacework-secrets
      valuesKey: serverUrl
      targetPath: laceworkConfig.serverUrl