---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubearmor
  namespace: kubearmor
spec:
  chart:
    spec:
      chart: kubearmor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubearmor
        namespace: flux-system
      version: "v0.10.2"
  interval: 1m0s
  releaseName: kubearmor
  targetNamespace: kubearmor
