apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "441"
  commitHash: 6e0f8e74037f1ff78daa5842b4e8b5f739a0ad85
  deployed: "1773777666"
  env: baremetal
