apiVersion: batch/v1
kind: Job
metadata:
  name: sample-rover-manifestjob
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo sleeping....; sleep 5s; exit 0;
      restartPolicy: Never
