---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic-testjob-service-account
  namespace: newrelic
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newrelic-testjob-role
  namespace: newrelic
rules:
- apiGroups: ["*"]
  resources: ["pods","secret"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newrelic-testjob-clusterrole-binding
  namespace: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic-testjob-service-account
  namespace: newrelic
roleRef:
  kind: ClusterRole
  name: newrelic-testjob-role
  apiGroup: rbac.authorization.k8s.io
