apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aqua-secretstore-eksa
  namespace: aqua
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store
    kind: ClusterSecretStore
  target:
    name: aqua-secrets-from-ps          # Specify the name for the Kubernetes Secret
  data:
    - secretKey: aqua-enforcer-token    # Key in Kubernetes Secret
      remoteRef:
        key: /aqua-enforcer/enforcer-token  # Key in AWS Parameter Store

    - secretKey: aqua-image-username
      remoteRef:
        key: /aqua-enforcer/username

    - secretKey: aqua-image-password
      remoteRef:
        key: /aqua-enforcer/password

    - secretKey: aqua-geteway-address
      remoteRef:
        key: /aqua-enforcer/gateway

