apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-configmap
  namespace: datakit
  labels:
    bot: conformitron
data:
  Namespace: datakit
  prNumber: "377"
  commitHash: 1f249f762769508f6968ffcd9d59fd98c6ead385
  deployed: "1755126456"
  env: common
