apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-configmap
  namespace: datakit
  labels:
    bot: conformitron
data:
  Namespace: datakit
  prNumber: "377"
  commitHash: 481fee51db42df5b9de2b9b34f71d002835f5299
  deployed: "1754837646"
  env: common
