---
# 仓库说明的本地测试部分有介绍如何拉取密钥
# 计划使用密钥存储token，如果集群名称无法在仓库管理，则将它作为configmap，或者将dataway和集群名称均作为configmap存储，总之不能
#   出现在仓库中
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datakit-external-secret
  namespace: datakit
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store # The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: datakit-secret # Secret name in k8s
  data:
  - secretKey: dataway # which key it's going to be stored
    remoteRef:
      key: dataway # Our secret-name goes here