---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datakit-external-secret
  namespace: datakit
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store # The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: datakit-secret # Secret name in k8s
  data:
  - secretKey: dataway_url # Which key it's going to be stored
    remoteRef:
      key: aws_service_ready # Our secret-name goes here
      property: dataway_url
  - secretKey: cluster_name_k8s # Which key it's going to be stored
    remoteRef:
      key: aws_service_ready # Our secret-name goes here
      property: cluster_name_k8s
