apiVersion: batch/v1
kind: CronJob
metadata:
  name: wave-autoscale-healthcheck
  namespace: wave-autoscale
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wave-autoscale-healthcheck
              image: alpine/k8s:1.26.9
              command:
                - /bin/sh
              args:
                - -c
                - |
                  echo "Start a health check for Wave Autoscale";

                  # Core health check
                  response=$(curl -s -w "\n200" http://wave-autoscale-svc.wave-autoscale.svc.cluster.local:3024/)
                  status_code=$(echo "$response" | tail -n1);
                  if [ "$status_code" -ne 200 ]; then
                    echo "Failed to fetch Wave Autoscale Core. Response was $response";
                    exit 1;
                  fi
                  echo "Wave Autoscale Core working Successful.";

                  # License check
                  response=$(curl -s -w "\n200" http://wave-autoscale-svc.wave-autoscale.svc.cluster.local:3024/api/info);
                  status_code=$(echo "$response" | tail -n1);
                  body=$(echo "$response" | head -n-1);
                  if [ "$status_code" -ne 200 ]; then
                    echo "Wave Autoscale License is invalid. Response was $response";
                    exit 1;
                  fi
                  license=$(echo "$body" | jq -r '.license');
                  if [ "$license" = "{}" ]; then
                    echo "Wave Autoscale License is invalid: empty map detected.";
                    exit 1;
                  fi
                  echo "Wave Autoscale License is valid.";

                  # Web Console health check
                  response=$(curl -s -w "\n200" http://wave-autoscale-svc.wave-autoscale.svc.cluster.local:3025/);
                  status_code=$(echo "$response" | tail -n1);
                  if [ "$status_code" -ne 200 ]; then
                    echo "Failed to fetch Wave Autoscale Web Console. Response was $response";
                    exit 1;
                  fi
                  echo "Wave Autoscale Web Console working Successful.";

                  # Autopilot health check
                  response=$(curl -s -w "\n200" http://wave-autoscale-svc.wave-autoscale.svc.cluster.local:3026/);
                  status_code=$(echo "$response" | tail -n1);
                  if [ "$status_code" -ne 200 ]; then
                    echo "Failed to fetch Wave Autoscale Autopilot. Response was $response";
                    exit 1;
                  fi
                  echo "Wave Autoscale Autopilot working Successful.";

                  exit 0;
          restartPolicy: Never
      backoffLimit: 1
