---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nutanix-storage
  namespace: ntnx-system
spec:
  chart:
    spec:
      chart: nutanix/nutanix-csi-storage
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nutanix
        namespace: ntnx-system
      version: "2.6.1"
  interval: 60s
  targetNamespace: ntnx-system
  values: 
    volumeClass: true
    fsType: xfs
    storageContainer: Default
    defaultStorageClass: volume
  valuesFrom:
  - kind: Secret
    name: nutanix-secret
    valuesKey: nutanix-endpoint
    targetPath: prismEndPoint
  - kind: Secret
    name: nutanix-secret
    valuesKey: nutanix-username
    targetPath: username
  - kind: Secret
    name: nutanix-secret
    valuesKey: nutanix-password
    targetPath: password

  
