apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nutanix-secret
  namespace: ntnx-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: nutanix-secret # Secret name in k8s
  data:
  - secretKey: nutanix-endpoint # which key it's going to be stored
    remoteRef:
      key: nutanix-endpoint # Our secret-name goes here
  - secretKey: nutanix-username # which key it's going to be stored
    remoteRef:
      key: nutanix-username # Our secret-name goes here
  - secretKey: nutanix-password # which key it's going to be stored
    remoteRef:
      key: nutanix-password # Our secret-name goes here
