---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dynatrace-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dynatrace-operator
      sourceRef:
        kind: HelmRepository
        name: dynatrace-operator-oci
        namespace: flux-system
      # version: "1.3.2"
  install:
    crds: CreateReplace
  interval: 1m0s
  targetNamespace: dynatrace
  upgrade:
    crds: CreateReplace
  values:
    installCRD: true
