---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dynatrace-external-secret
  namespace: dynatrace
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: dt-secret # Secret name in k8s
  dataFrom:
  - extract:
      # we expect an external secret in the following format
      # {"apiToken":"sometoken","dataIngestToken":"anothertoken"}
      key: dt-tokens-secret