---
apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace
  labels:
    aws.conformance.vendor: dynatrace
    aws.conformance.vendor-solution: dynatrace
    aws.conformance.vendor-solution-version: 0.10.1