apiVersion: batch/v1
kind: CronJob
metadata:
  name: risingwave-tester
  namespace: risingwave
spec:
  schedule: "*/10 * * * *" # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: risingwave-tester
            image: postgres:15
            env:
            - name: PGHOST
              value: "risingwave-frontend.risingwave.svc.cluster.local"
            - name: PGPORT
              value: "4566"
            - name: PGDATABASE
              value: "dev"
            - name: PGUSER
              value: "root"
            - name: PGPASSWORD
              value: ""
            command: ["/bin/sh", "-c"]
            args:
            - |
              set -e
              echo "--- RisingWave Tester Job ---"
              echo "Creating table..."
              psql -c "CREATE TABLE IF NOT EXISTS tester_table (id int, name varchar);"
              echo "Inserting data..."
              psql -c "INSERT INTO tester_table VALUES (1, 'test_name');"
              echo "Selecting data..."
              psql -c "SELECT * FROM tester_table;"
              echo "Dropping table..."
              psql -c "DROP TABLE tester_table;"
              echo "--- Test Successful ---"
          restartPolicy: Never
