apiVersion: v1
kind: Namespace
metadata:
  name: tetrate-istio-system
  labels:
    istio.io/rev: 1-18-1
    aws.conformance.vendor: tetrate.io
    aws.conformance.vendor-solution: tetrate-istio-distribution
    aws.conformance.vendor-solution-version: 1.18.1
