apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "401"
  commitHash: b24c08b592a6c0cbe474f0308a773e49fe45125b
  deployed: "1758629017"
  env: snow
