apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "439"
  commitHash: bd216ad797ad46d180430852b35ed1da5b4b7b54
  deployed: "1773179109"
  env: snow
