apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-configmap
  namespace: newrelic
  labels:
    bot: conformitron
data:
  Namespace: newrelic
  prNumber: "361"
  commitHash: 6c20cf9e3d12f9a7fb12fcaa77a29fb7cafe23b0
  deployed: "1745928242"
  env: snow
