---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic
  namespace: newrelic
spec:
  chart:
    spec:
      chart: nri-bundle
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: newrelic-charts
        namespace: flux-system
      version: 5.0.86
  interval: 1m0s
  targetNamespace: newrelic
  values:
    global:
      cluster: eks-conformance-testing
      lowDataMode: false
    newrelic-infrastructure:
      controlPlane:
        enabled: false
      privileged: false
      common:
        config:
          interval: 40s
          namespaceSelector:
            matchLabels:
              scrape: "true"
    kube-state-metrics:
      image:
        tag: v2.6.0
      enabled: true
    nri-metadata-injection:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: newrelic-secret
      valuesKey: newrelic-licensekey
      targetPath: global.licenseKey
      # - kind: ConfigMap
      #   name: aws-env-metadata
      #   namespace: kube-system
      #   valuesKey: clusterName
      #   targetPath: global.cluster
